### ISSUE TITLE
braker.pl: command not found

### ISSUE THREAD

**Issue by JuFengWang** [iii-companion/companion#31]
Hello!
I encountered some errors when running companion in my computer. The version of docker image is 
`uofgiii/companion           latest    0aa29699f086   11 months ago   4.28GB`

1.
```
Error executing process > 'nucmer_for_circos (1)'

Caused by:
  Process `nucmer_for_circos (1)` terminated with an error exit status (1)

Command executed:

  gunzip -f pseudo.fasta.gz
  nucmer --batch 1 refseq.fasta pseudo.fasta
  show-coords -B out.delta |           awk 'BEGIN{OFS="	"}{ print $1, $8, $13, $15, 0, 0, $9, $10, $11, $12, 0, 0}'           > nucmerout.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  Unknown option: batch
  
    USAGE: nucmer  [options]  <Reference>  <Query>
      
  Try '/usr/bin/nucmer -h' for more information.
```

2.
```
Error executing process > 'run_braker_pseudo'

Caused by:

  Process `run_braker_pseudo` terminated with an error exit status (127)

Command executed:

  echo "##gff-version 3
  " > braker.tmp;
      braker.pl --genome=pseudo.pseudochr.fasta --prot_seq=ann_prot.fasta       --species=augustus_species --useexisting --gff3 --cores 8
      gt gff3 -sort -tidy -retainids braker/braker.gff3 > 1
      if [ -s 1 ]; then
          gt select -mingenescore 0.8 1         > braker.tmp;
      fi
      augustus_mark_partial.lua braker.tmp > braker.gff3

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 4: braker.pl: command not found
```
For error 1, I have deleted the option "--batch 1“ in annot.nf, and it seems to be working fine for process `nucmer_for_circos (1)`. I am wondering how to solve these errors.

**Comment by haessar** [comment]
Hello @JuFengWang, thanks for highlighting this.

Today I've merged a change to the master branch updating ORTHOMCL from v1.4 to v2, and updated the uofgiii/companion:latest container on Docker Hub. The error that you saw regarding BRAKER will also be resolved as that was another recent addition that hadn't been reflected in the docker container.

Please feel free to pull the latest code and the latest container and try your job again. NOTE there is an additional setup step in the README now (see 2a). Let me know how you get on.

Best,

Will

**Comment by JuFengWang** [comment]
Thank fro your help. Today I have update the docker image and companion code, but the braker.pl is still not working properly.

```
Error executing process > 'run_braker_pseudo'

Caused by:
  Process `run_braker_pseudo` terminated with an error exit status (1)

Command executed:

  echo "##gff-version 3
  " > braker.tmp;
      AUGUSTUS_CONFIG_PATH=/home/try/WJF/soft/companion/example-data/references/LmjF.1     braker.pl --genome=pseudo.pseudochr.fasta --prot_seq=ann_prot.fasta       --species=augustus_species --useexisting --gff3 --cores 4
      gt gff3 -sort -tidy -retainids braker/braker.gff3 > 1
      if [ -s 1 ]; then
          gt select -mingenescore 0.8 1         > braker.tmp;
      fi
      augustus_mark_partial.lua braker.tmp > braker.gff3

Command exit status:
  1

Command output:
  (empty)

Command error:
  #**********************************************************************************
  #                               BRAKER CONFIGURATION                               
  #**********************************************************************************
  # BRAKER CALL: /opt/BRAKER/scripts/braker.pl --genome=pseudo.pseudochr.fasta --prot_seq=ann_prot.fasta --species=augustus_species --useexisting --gff3 --cores 4
  # Thu Sep 15 05:11:24 2022: braker.pl version 2.1.6
  # Thu Sep 15 05:11:24 2022: REMARK: Protein input detected, BRAKER will be executed in the EP mode (--epmode).
  # Thu Sep 15 05:11:24 2022: Configuring of BRAKER for using external tools...
  # Thu Sep 15 05:11:24 2022: Found environment variable $AUGUSTUS_CONFIG_PATH. Setting $AUGUSTUS_CONFIG_PATH to /home/try/WJF/soft/companion/example-data/references/LmjF.1
  # Thu Sep 15 05:11:24 2022: Found environment variable $AUGUSTUS_BIN_PATH. Setting $AUGUSTUS_BIN_PATH to /opt/Augustus/bin
  # Thu Sep 15 05:11:24 2022: Found environment variable $AUGUSTUS_SCRIPTS_PATH. Setting $AUGUSTUS_SCRIPTS_PATH to /opt/Augustus/scripts
  # Thu Sep 15 05:11:24 2022: Found environment variable $PYTHON3_PATH. Setting $PYTHON3_PATH to /usr/bin
  # Thu Sep 15 05:11:24 2022: Found environment variable $GENEMARK_PATH. Setting $GENEMARK_PATH to /opt/gmes_linux_64_4
  # Thu Sep 15 05:11:24 2022: Found environment variable $DIAMOND_PATH. Setting $DIAMOND_PATH to /opt
  # Thu Sep 15 05:11:24 2022: Found environment variable $PROTHINT_PATH. Setting $PROTHINT_PATH to /opt/ProtHint/bin
  # Thu Sep 15 05:11:24 2022: Did not find environment variable $CDBTOOLS_PATH
  # Thu Sep 15 05:11:24 2022: Trying to guess $CDBTOOLS_PATH from location of cdbfasta executable that is available in your $PATH
  # Thu Sep 15 05:11:24 2022: Setting $CDBTOOLS_PATH to /usr/bin
  # Thu Sep 15 05:11:24 2022: BRAKER will execute GeneMark-EP for training GeneMark and generating a training gene set for AUGUSTUS, using protein information as sole extrinsic evidence source.
  # Thu Sep 15 05:11:24 2022: ERROR: in file /opt/BRAKER/scripts/braker.pl at line 4720
  protein sequence file ann_prot.fasta does not exist.
```
I am looking forward to hearing from you ！

**Comment by haessar** [comment]
Hi @JuFengWang,

I've gone ahead and updated the example-data references (e.g. LmjF.1) in the code so that they work with the latest additions. Please could I ask that you update your companion source code once more and re-pull the uofgiii/companion:latest docker image, and try again. Thanks for your patience with this, your findings are proving a useful test case!

Best,

Will

**Comment by JuFengWang** [comment]
```
N E X T F L O W  ~  version 22.04.5
Launching `companion_1/annot.nf` [crazy_hopper] DSL1 - revision: ed72225d2a

C O M P A N I O N  ~  version 1.0.2
query               : /home/try/WJF/soft/companion_1/example-data/L_donovani.1.fasta
reference           : LmjF_01
reference directory : /home/try/WJF/soft/companion_1/example-data/references
output directory    : /home/try/WJF/soft/companion_1/example-output

executor >  local (2)
[fd/e62e07] process > truncate_input_headers         [  0%] 0 of 1
[-        ] process > sanitize_input                 -
[-        ] process > contiguate_pseudochromosomes   -
[-        ] process > predict_tRNA                   -
executor >  local (3)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[-        ] process > sanitize_input                 [  0%] 0 of 1
[-        ] process > contiguate_pseudochromosomes   -
[-        ] process > predict_tRNA                   -
executor >  local (4)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[-        ] process > sanitize_input                 [  0%] 0 of 1
[-        ] process > contiguate_pseudochromosomes   -
[-        ] process > predict_tRNA                   -
executor >  local (5)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[-        ] process > sanitize_input                 [  0%] 0 of 1
[-        ] process > contiguate_pseudochromosomes   -
[-        ] process > predict_tRNA                   -
executor >  local (6)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[-        ] process > sanitize_input                 [  0%] 0 of 1
[-        ] process > contiguate_pseudochromosomes   -
[-        ] process > predict_tRNA                   -
executor >  local (7)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[-        ] process > sanitize_input                 [  0%] 0 of 1
[-        ] process > contiguate_pseudochromosomes   -
[-        ] process > predict_tRNA                   -
executor >  local (8)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[-        ] process > sanitize_input                 [  0%] 0 of 1
[-        ] process > contiguate_pseudochromosomes   -
[-        ] process > predict_tRNA                   -
executor >  local (9)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[eb/2565f0] process > sanitize_input                 [  0%] 0 of 1
[-        ] process > contiguate_pseudochromosomes   -
[-        ] process > predict_tRNA                   -
executor >  local (10)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[eb/2565f0] process > sanitize_input                 [  0%] 0 of 1
[-        ] process > contiguate_pseudochromosomes   -
[-        ] process > predict_tRNA                   -
[df/46a5cc] process > press_ncRNA_cms                [100%] 1 of 1 ✔
executor >  local (10)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[eb/2565f0] process > sanitize_input                 [100%] 1 of 1 ✔
[-        ] process > contiguate_pseudochromosomes   -
[-        ] process > predict_tRNA                   -
[df/46a5cc] process > press_ncRNA_cms                [100%] 1 of 1 ✔
executor >  local (11)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[eb/2565f0] process > sanitize_input                 [100%] 1 of 1 ✔
[ae/ec9c2c] process > contiguate_pseudochromosomes   [  0%] 0 of 1
[-        ] process > predict_tRNA                   -
[df/46a5cc] process > press_ncRNA_cms                [100%] 1 of 1 ✔
executor >  local (11)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[eb/2565f0] process > sanitize_input                 [100%] 1 of 1 ✔
[ae/ec9c2c] process > contiguate_pseudochromosomes   [  0%] 0 of 1
[-        ] process > predict_tRNA                   -
[df/46a5cc] process > press_ncRNA_cms                [100%] 1 of 1 ✔
executor >  local (13)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[eb/2565f0] process > sanitize_input                 [100%] 1 of 1 ✔
[ae/ec9c2c] process > contiguate_pseudochromosomes   [100%] 1 of 1 ✔
[d5/0035a5] process > predict_tRNA                   [  0%] 0 of 1
[df/46a5cc] process > press_ncRNA_cms                [100%] 1 of 1 ✔
executor >  local (14)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[eb/2565f0] process > sanitize_input                 [100%] 1 of 1 ✔
[ae/ec9c2c] process > contiguate_pseudochromosomes   [100%] 1 of 1 ✔
[d5/0035a5] process > predict_tRNA                   [100%] 1 of 1 ✔
[df/46a5cc] process > press_ncRNA_cms                [100%] 1 of 1 ✔
executor >  local (15)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[eb/2565f0] process > sanitize_input                 [100%] 1 of 1 ✔
[ae/ec9c2c] process > contiguate_pseudochromosomes   [100%] 1 of 1 ✔
[d5/0035a5] process > predict_tRNA                   [100%] 1 of 1 ✔
[df/46a5cc] process > press_ncRNA_cms                [100%] 1 of 1 ✔
executor >  local (16)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[eb/2565f0] process > sanitize_input                 [100%] 1 of 1 ✔
[ae/ec9c2c] process > contiguate_pseudochromosomes   [100%] 1 of 1 ✔
[d5/0035a5] process > predict_tRNA                   [100%] 1 of 1 ✔
[df/46a5cc] process > press_ncRNA_cms                [100%] 1 of 1 ✔
[5a/8c4c30] process > predict_ncRNA (1)              [  0%] 0 of 1
executor >  local (17)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[eb/2565f0] process > sanitize_input                 [100%] 1 of 1 ✔
[ae/ec9c2c] process > contiguate_pseudochromosomes   [100%] 1 of 1 ✔
[d5/0035a5] process > predict_tRNA                   [100%] 1 of 1 ✔
[df/46a5cc] process > press_ncRNA_cms                [100%] 1 of 1 ✔
[5a/8c4c30] process > predict_ncRNA (1)              [  0%] 0 of 1
executor >  local (18)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[eb/2565f0] process > sanitize_input                 [100%] 1 of 1 ✔
[ae/ec9c2c] process > contiguate_pseudochromosomes   [100%] 1 of 1 ✔
[d5/0035a5] process > predict_tRNA                   [100%] 1 of 1 ✔
[df/46a5cc] process > press_ncRNA_cms                [100%] 1 of 1 ✔
[5a/8c4c30] process > predict_ncRNA (1)              [  0%] 0 of 1
[-        ] process > merge_ncrnas                   -
[85/ceedf0] process > exonerate_empty_hints          [100%] 1 of 1 ✔
[1d/577cf0] process > ratt_make_ref_embl             [100%] 1 of 1 ✔
[4a/dd0e0e] process > run_ratt                       [100%] 1 of 1 ✔
[-        ] process > ratt_to_gff3                   [  0%] 0 of 1
[23/96347c] process > transcript_empty_hints         [100%] 1 of 1 ✔
[e6/a7279a] process > merge_hints                    [100%] 1 of 1 ✔
[-        ] process > run_braker_pseudo              [  0%] 0 of 1
[c9/bacb1a] process > run_braker_contigs             [  0%] 0 of 1
[30/103f3b] process > run_snap                       [100%] 1 of 1 ✔
[-        ] process > merge_genemodels               -
[-        ] process > integrate_genemodels           -
[-        ] process > fix_polycistrons               -
[-        ] process > remove_exons                   -
[98/58c102] process > pseudogene_indexing            [100%] 1 of 1 ✔
[ca/6a6dc2] process > pseudogene_last (1)            [  0%] 0 of 1
[-        ] process > pseudogene_calling             -
[-        ] process > merge_structural               -
[-        ] process > add_gap_features               -
[-        ] process > split_splice_models_at_gaps    -
[-        ] process > add_polypeptides               -
[-        ] process > get_proteins_for_orthomcl      -
[73/f205a2] process > make_ref_input_for_orthomcl    [100%] 1 of 1 ✔
[-        ] process > make_target_input_for_orthomcl -
[-        ] process > filter_fasta_for_orthomcl      -
[-        ] process > blast_for_orthomcl_formatdb    -
[-        ] process > blast_for_orthomcl             -
[-        ] process > parse_blastout_for_orthomcl    -
[cd/ec4d6b] process > drop_orthomcl_schema           [100%] 1 of 1, failed: 1 ✔
[-        ] process > run_orthomcl                   -
[-        ] process > annotate_orthologs             -
[-        ] process > run_pfam                       -
[-        ] process > pfam_to_gff3                   -
[-        ] process > annotate_pfam                  -
[-        ] process > make_distribution_gff          -
[-        ] process > make_distribution_gaf          -
[10/6f2fc8] process > make_distribution_seqs         [100%] 1 of 1 ✔
[-        ] process > make_genome_stats              -
[-        ] process > reference_compare              -
[-        ] process > make_tree                      -
[-        ] process > nucmer_for_circos              [  0%] 0 of 1
[-        ] process > make_circos_inputs             -
[-        ] process > circos_run_chrs                -
[-        ] process > circos_run_bin                 -
[-        ] process > merge_gff3_for_gff3toembl      -
[-        ] process > make_embl                      -
[-        ] process > make_report                    -
[-        ] process > make_genelist                  -
[-        ] process > add_products_to_protein_fasta  -
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition -- check channel `ncrna_cmindex`
executor >  local (18)
[fd/e62e07] process > truncate_input_headers         [100%] 1 of 1 ✔
[eb/2565f0] process > sanitize_input                 [100%] 1 of 1 ✔
[ae/ec9c2c] process > contiguate_pseudochromosomes   [100%] 1 of 1 ✔
[d5/0035a5] process > predict_tRNA                   [100%] 1 of 1 ✔
[df/46a5cc] process > press_ncRNA_cms                [100%] 1 of 1 ✔
[-        ] process > predict_ncRNA (1)              -
[-        ] process > merge_ncrnas                   -
[85/ceedf0] process > exonerate_empty_hints          [100%] 1 of 1 ✔
[1d/577cf0] process > ratt_make_ref_embl             [100%] 1 of 1 ✔
[4a/dd0e0e] process > run_ratt                       [100%] 1 of 1 ✔
[-        ] process > ratt_to_gff3                   [  0%] 0 of 1
[23/96347c] process > transcript_empty_hints         [100%] 1 of 1 ✔
[e6/a7279a] process > merge_hints                    [100%] 1 of 1 ✔
[-        ] process > run_braker_pseudo              [  0%] 0 of 1
[c9/bacb1a] process > run_braker_contigs             [100%] 1 of 1, failed: 1 ✘
[30/103f3b] process > run_snap                       [100%] 1 of 1 ✔
[-        ] process > merge_genemodels               -
[-        ] process > integrate_genemodels           -
[-        ] process > fix_polycistrons               -
[-        ] process > remove_exons                   -
[98/58c102] process > pseudogene_indexing            [100%] 1 of 1 ✔
[-        ] process > pseudogene_last (1)            -[-        ] process > pseudogene_calling             -
[-        ] process > merge_structural               -
[-        ] process > add_gap_features               -
[-        ] process > split_splice_models_at_gaps    -
[-        ] process > add_polypeptides               -
[-        ] process > get_proteins_for_orthomcl      -
[73/f205a2] process > make_ref_input_for_orthomcl    [100%] 1 of 1 ✔
[-        ] process > make_target_input_for_orthomcl -
[-        ] process > filter_fasta_for_orthomcl      -
[-        ] process > blast_for_orthomcl_formatdb    -
[-        ] process > blast_for_orthomcl             -
[-        ] process > parse_blastout_for_orthomcl    -
[cd/ec4d6b] process > drop_orthomcl_schema           [100%] 1 of 1, failed: 1 ✔
[-        ] process > run_orthomcl                   -
[-        ] process > annotate_orthologs             -[-        ] process > run_pfam                       -
[-        ] process > pfam_to_gff3                   -
[-        ] process > annotate_pfam                  -
[-        ] process > make_distribution_gff          -[-        ] process > make_distribution_gaf          -
[10/6f2fc8] process > make_distribution_seqs         [100%] 1 of 1 ✔
[-        ] process > make_genome_stats              -
[-        ] process > reference_compare              -
[-        ] process > make_tree                      -
[-        ] process > nucmer_for_circos              [  0%] 0 of 1
[-        ] process > make_circos_inputs             -
[-        ] process > circos_run_chrs                -
[-        ] process > circos_run_bin                 -
[-        ] process > merge_gff3_for_gff3toembl      -
[-        ] process > make_embl                      -
[-        ] process > make_report                    -
[-        ] process > make_genelist                  -
[-        ] process > add_products_to_protein_fasta  -
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition -- check channel `ncrna_cmindex`
WARN: Access to undefined parameter `TRANSCRIPT_FILE` -- Initialise it to a default value eg. `params.TRANSCRIPT_FILE = some_value`
WARN: The access of `config` object is deprecated
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition -- check channel `pseudochr_last_index`
[cd/ec4d6b] NOTE: Process `drop_orthomcl_schema` terminated with an error exit status (2) -- Error is ignored
WARN: Access to undefined parameter `print_paths` -- Initialise it to a default value eg. `params.print_paths = some_value`
Error executing process > 'run_braker_contigs'

Caused by:
  Process `run_braker_contigs` terminated with an error exit status (1)

Command executed:

  echo "##gff-version 3
  " > braker.ctg.tmp;
      AUGUSTUS_CONFIG_PATH=/home/try/WJF/soft/companion_1/example-data/references/LmjF_01     braker.pl --genome=pseudo.contigs.fasta --prot_seq=ann_prot.fasta       --species=augustus_species --useexisting --gff3 --cores 4
      gt gff3 -sort -tidy -retainids braker/braker.gff3 > 1
      if [ -s 1 ]; then
          gt select -mingenescore 0.8 1         > braker.ctg.tmp;
      fi
      augustus_mark_partial.lua braker.ctg.tmp > braker.ctg.gff3
  
      transform_gff_with_agp.lua         braker.ctg.gff3         pseudo.scaffolds.agp         pseudo.contigs.fasta         pseudo.scaffolds.fasta |         gt gff3 -sort -tidy -retainids >         braker.ctg.scaf.mapped.gff3
      transform_gff_with_agp.lua         braker.ctg.scaf.mapped.gff3         pseudo.pseudochr.agp         pseudo.scaffolds.fasta         pseudo.pseudochr.fasta |         gt gff3 -sort -tidy -retainids >         braker.scaf.pseudo.mapped.gff3
      
      if [ ! -s braker.scaf.pseudo.mapped.gff3 ]; then
        echo '##gff-version 3' > braker.scaf.pseudo.mapped.gff3
      fi

Command exit status:
  1

Command output:
  # Tue Sep 20 07:46:38 2022: Log information is stored in file braker/braker.log

Command error:
  #*********
  # WARNING: Detected whitespace in fasta header of file ann_prot.fasta. This may later on cause problems! The pipeline will create a new file without spaces or "|" characters and a genome_header.map file to look up the old and new headers. This message will be suppressed from now on!
  #*********
  #*********
  # WARNING: Detected | in fasta header of file ann_prot.fasta. This may later on cause problems! The pipeline will create a new file without spaces or "|" characters and a genome_header.map file to look up the old and new headers. This message will be suppressed from now on!
  #*********
  ERROR in file /opt/BRAKER/scripts/braker.pl at line 6595
  Failed to execute: perl /opt/gmes_linux_64_4/gmes_petap.pl --verbose --cores=4 --ES --gc_donor 0.001 --sequence=braker/genome.fa  1>braker/GeneMark-ES.stdout 2>braker/errors/GeneMark-ES.stderr
  The most common problem is an expired or not present file ~/.gm_key!

Work dir:
  /home/try/WJF/soft/work/c9/bacb1adfe49d0e4a976e9d0fcf792f

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 ```
I am so sorry to tell you that the program still does not work. Besides, the name of LmjF is not consistent between references document and params_default.config.

**Comment by haessar** [comment]
Yes, well spotted with the params_default.config. I've updated it to LmjF_01 and turned off braker by default for local/docker runs (will use base Augustus instead, which was original behaviour). Please git pull latest companion code and retry (you don't need to pull from docker hub again though).

Thanks for your continued patience, and hopefully this time should work.

Will

**Comment by JuFengWang** [comment]
```
[ee/465ec5] process > drop_orthomcl_schema           [100%] 1 of 1, failed: 1 ✔
[-        ] process > run_orthomcl                   -
[-        ] process > annotate_orthologs             -
[-        ] process > run_pfam                       -
[-        ] process > pfam_to_gff3                   -
[-        ] process > annotate_pfam                  -
[-        ] process > make_distribution_gff          -
[-        ] process > make_distribution_gaf          -
[dd/dfddd9] process > make_distribution_seqs         [100%] 1 of 1 ✔
[-        ] process > make_genome_stats              -
[-        ] process > reference_compare              -
[-        ] process > make_tree                      -
[c3/774f77] process > nucmer_for_circos (1)          [  0%] 0 of 1
[-        ] process > make_circos_inputs             -
[-        ] process > circos_run_chrs                -
[-        ] process > circos_run_bin                 -
[-        ] process > merge_gff3_for_gff3toembl      -
[-        ] process > make_embl                      -
[-        ] process > make_report                    -
[-        ] process > make_genelist                  -
[-        ] process > add_products_to_protein_fasta  -
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition -- check channel `ncrna_cmindex`
WARN: Access to undefined parameter `TRANSCRIPT_FILE` -- Initialise it to a default value eg. `params.TRANSCRIPT_FILE = some_value`
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition -- check channel `pseudochr_last_index`
[ee/465ec5] NOTE: Process `drop_orthomcl_schema` terminated with an error exit status (22) -- Error is ignored
WARN: Access to undefined parameter `print_paths` -- Initialise it to a default value eg. `params.print_paths = some_value`

```
Thanks for your help, now the nextflow can work fine. But the Process `drop_orthomcl_schema` always failed in logs. Whether the failure will affect the annotation ？

**Comment by haessar** [comment]
Yes, that error can be safely ignored and won't impact the annotations. Glad that it's working. Let me know if you encounter any other issues.
Will
